name: clientes_iptv
description: "Gestor de clientes para servicios de IPTV."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  google_fonts: ^6.3.2
  fl_chart: ^0.68.0
  csv: ^6.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  file_picker: ^10.3.3
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
